stages:
  - test
  - sonarqube
  - publish


test:
  stage: test
  image: node:22
  script:
    - npm install
    - npm run coverage
  artifacts:
    paths:
      - coverage/

sonarqube-check:
  stage: sonarqube
  image: node:22
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    TMPDIR: "/tmp"   # Use system temp directory
    GIT_DEPTH: "0"
    SONAR_HOST_URL: "https://dev-sonar.irrational.cc"
    SONAR_TOKEN: "${SONAR_TOKEN}"
  before_script:
    - npm install -g sonarqube-scanner
    - chmod -R 777 /tmp   # Ensure /tmp is writable
  script:
    - sonar-scanner -X
  allow_failure: true
  only:
    - dev-release
    - develop
  dependencies:
    - test




#  PUBLISH TO VERDACCIO STAGE
publish:
  stage: publish
  image: node:22
  script:
    - npm config set registry https://dev-verdaccio.irrational.cc
    - npm config set strict-ssl false
    - echo "//dev-verdaccio.irrational.cc/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
    - npm version prerelease --preid=${CI_PIPELINE_ID} --no-git-tag-version  # Append pipeline ID as pre-release
    - npm publish --registry https://dev-verdaccio.irrational.cc
  only:
    - dev-release
  dependencies:
    - test


